### ISSUE TITLE
Setting up mongo server/starting your own instance

### ISSUE THREAD

**Issue by almeida2808** [Just-Fans-Of/Impromp2#20]
First of all, congrats on the good work.

The bot seems to be offline for a while and I would like to add it to a Discord channel. README.md gives a very brief description of how to start your own instance, but it isnt clear and deep enough for me. Should I set up a Mongo server? How do I do that? Should I open a specific kind of server? Where do I get the 2 collections and 1 document required? I guess that pointing me to the relevant links should suffice. Thanks anyway.

**Comment by MedicOP** [comment]
Same problem. I have the Mongo stuff set up but how do you start up the bot? Do we need node.js or something?

**Comment by MedicOP** [comment]
Can confirm you need node.js

**Comment by MedicOP** [comment]
Getting this error though

```javascript
info: Connected to database
info: exception Shutting down...
info: TypeError: Cannot read property '_id' of null
    at new GlobalConfig (/home/impromp2/config.js:93:23)
    at res.findOne (/home/impromp2/index.js:139:37)
    at handleCallback (/home/impromp2/node_modules/mongodb/lib/utils.js:120:56)
    at /home/impromp2/node_modules/mongodb/lib/collection.js:1417:5
    at handleCallback (/home/impromp2/node_modules/mongodb/lib/utils.js:120:56)
    at /home/impromp2/node_modules/mongodb/lib/cursor.js:682:5
    at handleCallback (/home/impromp2/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorNotified (/home/impromp2/node_modules/mongodb-core/lib/cursor.js:515:3)
    at /home/impromp2/node_modules/mongodb-core/lib/cursor.js:590:16
    at queryCallback (/home/impromp2/node_modules/mongodb-core/lib/cursor.js:253:5)
/home/impromp2/index.js:70
                if (exports.config.global.isDirty()) {
                                         ^

TypeError: Cannot read property 'isDirty' of undefined
    at Object.save (/home/impromp2/index.js:70:42)
    at exitHandler (/home/impromp2/index.js:155:24)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)
```
